<?php
/**
 * Class Authenticator
 * This class includes functions for managing the TOTP authenticator.
 * It allows the setting and getting of the algorithm used, the length of the generated code, and the time-step size in seconds.
 * @Authenticator
 * @author Onur Kudret
 * @version 1.0.0
 */

namespace FusionAuthIntegrationBundle\Instance\User\TwoFactor;

use FusionAuthIntegrationBundle\Utils\Serializable\Serializable;

/**
 * @Authenticator Instance of Authenticator
 * @implements Serializable
 */
class Authenticator extends Serializable
{
    /**
     * @var string|null
     * The algorithm used by the TOTP authenticator. With the current implementation, this will always be HmacSHA1
     */
    protected ?string $algorithm = null;
    /**
     * @var int|null
     * The length of code generated by the TOTP. With the current implementation, this will always be 6.
     */
    protected ?int $codeLength = null;
    /**
     * @var int|null
     * The time-step size in seconds. With the current implementation, this will always be 30.
     */
    protected ?int $timeStep = null;

    /**
     * Get Algorithm
     *
     * @return string|null Returns the name of algorithm used by TOTP authenticator.
     */
    public function getAlgorithm(): ?string
    {
        return $this->algorithm;
    }

    /**
     * Set Algorithm
     *
     * @param string|null $algorithm Name of algorithm to be set for the TOTP authenticator.
     */
    public function setAlgorithm(?string $algorithm): static
    {
        $this->algorithm = $algorithm;

        return $this;
    }

    /**
     * Get Code Length
     *
     * @return int|null Returns the length of code generated by the TOTP.
     */
    public function getCodeLength(): ?int
    {
        return $this->codeLength;
    }

    /**
     * Set Code Length
     *
     * @param int|null $codeLength Length of code to be set for the TOTP authenticator.
     */
    public function setCodeLength(?int $codeLength): static
    {
        $this->codeLength = $codeLength;

        return $this;
    }

    /**
     * Get Time Step
     *
     * @return int|null Returns the time-step size in seconds.
     */
    public function getTimeStep(): ?int
    {
        return $this->timeStep;
    }

    /**
     * Set Time Step
     *
     * @param int|null $timeStep Time-step size in seconds to be set for the TOTP authenticator.
     */
    public function setTimeStep(?int $timeStep): static
    {
        $this->timeStep = $timeStep;

        return $this;
    }
}